### ISSUE TITLE
Nitr0 not working on Minecraft x86 (1.18)

### ISSUE THREAD

**Issue by Rat0tey** [javajarr/Nitr0#1]
nitr0 stopped working on x86 version of Minecraft and does not inject modules: Reach, Timer, Velocity. before I used only reach because in the version that was released before the Reach module and velocity the timer didn't appear to be configurable, but only for reach it worked, the speed even had to change the configuration but it didn't work. this was on minecraft x86 versions 1.17.

please update the client if possible to work on x86 versions of minecraft bedrock

nitr0 >>> all

**Comment by master7720** [comment]
good.
